#pragma warning disable CS1591
using System.ComponentModel;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis;

[EditorBrowsable(EditorBrowsableState.Never)]
public static class IncrementalGeneratorInitializationContextExtensions
{
	extension(IncrementalGeneratorInitializationContext context)
	{
		/// <summary>
		/// Registers the <c>Microsoft.CodeAnalysis.EmbeddedAttribute</c> source using a <see cref="CodeWriter"/>.
		/// </summary>
		/// <param name="fileName">The source file name.</param>
		/// <typeparam name="TGenerator">Generator type used to create the <see cref="GenerationSettings"/>.</typeparam>
		public IncrementalGeneratorInitializationContext RegisterEmbeddedAttribute<TGenerator>(
			string fileName = "EmbeddedAttribute.g.cs"
		) => RegisterEmbeddedAttribute(context, GenerationSettings.Create<TGenerator>(), fileName);

		/// <summary>
		/// Registers the <c>Microsoft.CodeAnalysis.EmbeddedAttribute</c> source using a <see cref="CodeWriter"/>.
		/// </summary>
		/// <param name="settings">The generation settings.</param>
		/// <param name="fileName">The source file name.</param>
		public IncrementalGeneratorInitializationContext RegisterEmbeddedAttribute(
			GenerationSettings settings,
			string fileName = "EmbeddedAttribute.g.cs"
		)
		{
			if (settings is null)
				throw new ArgumentNullException(nameof(settings));

			context.RegisterPostInitializationOutput(spc =>
			{
				CodeWriter writer = new(settings);
				writer.AutoGeneratedHeader();
				writer.FileScopedNamespace(
					PurviewTypeLibrary.Microsoft.CodeAnalysis.EmbeddedAttribute.AsTypeReference()
				);

				// The compiler treats this special type as implicitly compiler-generated and embedded,
				// so no generated attributes are applied here and it must remain internal (CS9271).
				writer.Class(
					new(PurviewTypeLibrary.Microsoft.CodeAnalysis.EmbeddedAttribute)
					{
						Accessibility = TypeDeclarationAccessibility.Internal,
						IsSealed = true,
						IsPartial = true,
						BaseType = PurviewTypeLibrary.System.Attribute,
						IncludeGeneratedAttributes = false,
					},
					bodyWriter =>
						bodyWriter.Comment(
							"This is a special type that is treated as implicitly compiler-generated and embedded by the compiler."
						)
				);

				spc.AddSource(fileName, SourceText.From(writer.ToString(), Encoding.UTF8));
			});

			return context;
		}

		/// <summary>
		/// Registers a source output that combines each <see cref="GeneratorResult{T}"/> with a
		/// generation context, reports any diagnostics, and invokes the generator callback only for
		/// successful results. This keeps generator <see cref="IIncrementalGenerator.Initialize"/> methods thin
		/// and enforces the rule that diagnostics are reported in the source output stage.
		/// </summary>
		public IncrementalGeneratorInitializationContext RegisterSourceOutput<TOutput, TCapabilities>(
			IncrementalValuesProvider<GeneratorResult<TOutput>> outputs,
			IncrementalValueProvider<GenerationContext<TCapabilities>> contextProvider,
			Action<SourceProductionContext, TOutput, GenerationContext<TCapabilities>> generate,
			string? trackingName = null
		)
			where TOutput : notnull
			where TCapabilities : class, IGenerationCapabilities
		{
			if (generate is null)
				throw new ArgumentNullException(nameof(generate));

			var combined = outputs
				.CombineWith(contextProvider, static (output, ctx, _) => (Output: output, Context: ctx))
				.WithTrackingName(trackingName ?? $"RegisterSourceOutput_{typeof(TOutput).Name}");

			context.RegisterSourceOutput(
				combined,
				(spc, item) =>
				{
					if (item.Output.HasDiagnostics)
						spc.ReportDiagnostics(item.Output.Diagnostics);

					if (!item.Output.ShouldProcess)
						return;

					generate(spc, item.Output.Value, item.Context);
				}
			);

			return context;
		}
	}
}
