using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Purview.SourceGeneratorFramework.Examples;

/// <summary>
/// Emits the <c>GenerateCodeWriterSampleAttribute</c> and the sample class generated by
/// <see cref="CodeWriterSampleGenerator"/>, demonstrating the structured <see cref="CodeWriter"/> API.
/// </summary>
static class CodeWriterSampleEmitter
{
	/// <summary>
	/// Emits the <c>GenerateCodeWriterSampleAttribute</c> marker attribute.
	/// </summary>
	public static void EmitAttribute(IncrementalGeneratorPostInitializationContext spc)
	{
		CodeWriter writer = new(GenerationSettings.Create<CodeWriterSampleGenerator>(), throwOnUnclosedScopes: false);

		writer.AutoGeneratedHeader();
		writer.FileScopedNamespace(ExampleGenerator.PurviewTypeLibrary.GenerateCodeWriterSampleAttribute);

		writer.AttributeClass(
			ExampleGenerator.PurviewTypeLibrary.GenerateCodeWriterSampleAttribute.Name,
			TypeDeclarationAccessibility.Public,
			AttributeTargets.Class,
			_ => { },
			configure: options => (options with { IsPartial = false })
		);

		spc.AddSource("GenerateCodeWriterSampleAttribute.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
	}

	/// <summary>
	/// Emits the sample class demonstrating the minimal overloads, scoped declarations, structured
	/// statements, and <see cref="CodeWriter.NetConditionalReturn"/>.
	/// </summary>
	public static void Execute(SourceProductionContext spc, CodeWriterSampleTarget target)
	{
		if (string.IsNullOrWhiteSpace(target.TypeName))
			return;

		CodeWriter writer = new(GenerationSettings.Create<CodeWriterSampleGenerator>(), throwOnUnclosedScopes: false);

		writer.AutoGeneratedHeader();
		writer.PragmaDisable("CS8625");
		writer.FileScopedNamespace(target.Namespace ?? "Purview.SourceGeneratorFramework.Examples.Samples");

		writer.Comment("Generated by the CodeWriter sample generator.");

		writer.Class(
			target.TypeName + "CodeWriterSample",
			TypeDeclarationAccessibility.Public,
			options => options with { IsSealed = true, IsPartial = false },
			body =>
			{
				body.Field(
					"_value",
					TypeIdentity.Create<int>().AsTypeReference(),
					TypeDeclarationAccessibility.Private,
					options => options with { IsReadOnly = true }
				);

				body.Constructor(
					target.TypeName + "CodeWriterSample",
					TypeDeclarationAccessibility.Public,
					options =>
						options with
						{
							Parameters = [new("value", TypeIdentity.Create<int>().AsTypeReference())],
						},
					constructorBody => constructorBody.Assignment("_value", "value")
				);

				body.Property(
					"Value",
					TypeIdentity.Create<int>().AsTypeReference(),
					TypeDeclarationAccessibility.Public,
					options => options with { HasGetter = true }
				);

				// The accessibility is omitted, so the writer's default (public) is applied.
				body.Property("DefaultAccessibility", TypeIdentity.Create<string>().AsTypeReference());

				// A generic library type: constructed from the open definition in PurviewTypeLibrary.
				body.Property(
					"Items",
					PurviewTypeLibrary.System.Collections.Generic.IReadOnlyList.MakeGeneric(
						TypeIdentity.Create<string>()
					),
					TypeDeclarationAccessibility.Public
				);

				// The null literal: PurviewTypeLibrary.System.Null renders as the "null" value expression.
				body.Property(
					"Fallback",
					TypeIdentity.Create<string>().MakeNullable(body),
					TypeDeclarationAccessibility.Public,
					options => options with { HasSetter = true, Initializer = PurviewTypeLibrary.System.Null }
				);

				body.HashDefines(
					"NET",
					conditional => conditional.Comment("This member is emitted only for .NET targets.")
				);

				using (body.OpenPragmasScope("CS0618"))
				{
					body.Comment("Emitted with the warning suppressed.");
				}

				body.Method(
					"Describe",
					TypeIdentity.Create<string>().AsTypeReference(),
					TypeDeclarationAccessibility.Public,
					options =>
						options with
						{
							IsStatic = true,
							Parameters = [new("value", TypeIdentity.Create<int>().AsTypeReference())],
						},
					methodBody =>
					{
						methodBody.MethodCall("global::System.Console.WriteLine", "\"Describe\"");
						methodBody.Return("value.ToString()");
					}
				);

				using (
					body.MethodScope(
						"Format",
						TypeIdentity.Create<string>().AsTypeReference(),
						TypeDeclarationAccessibility.Public
					)
				)
					body.NetConditionalReturn("Value: {_value}");

				body.Method(
					"Categorize",
					TypeIdentity.Create<string>().AsTypeReference(),
					TypeDeclarationAccessibility.Public,
					options =>
						options with
						{
							IsStatic = true,
							Parameters = [new("value", TypeIdentity.Create<int>().AsTypeReference())],
						},
					methodBody =>
						methodBody
							.IfBlock("value < 0", branch => branch.Return("\"negative\""))
							.ElseIf("value == 0", branch => branch.Return("\"zero\""))
							.Else(branch => branch.Return("\"positive\""))
				);

				body.Method(
					"Configure",
					TypeIdentity.Create<string>().AsTypeReference(),
					TypeDeclarationAccessibility.Public,
					options =>
						options with
						{
							IsStatic = true,
							Parameters =
							[
								new("source", TypeIdentity.Create<string>().AsTypeReference()),
								new("onBuilt", PurviewTypeLibrary.System.Action.AsTypeReference()),
							],
						},
					methodBody =>
					{
						methodBody.Assignment(
							"var hostKitOptions",
							expression =>
								expression.MethodCallChain(
									"source.Trim",
									[],
									chain => chain.Method("ToUpper").Postfix(" ?? string.Empty")
								)
						);
						methodBody.Assignment(
							"var",
							"optionsBuilder",
							expression =>
								expression.MethodCallChain(
									"global::System.Array.Empty",
									[],
									chain => chain.Method("Clone"),
									genericArguments:
									[
										new TypeReference(new TypeIdentity("global::System.String", null)),
									]
								)
						);
						methodBody.MethodCallOn("onBuilt", "Invoke", [], nullConditional: true);
						methodBody.Return("hostKitOptions");
					}
				);

				body.Method(
					"Create",
					TypeIdentity.Create<string>().AsTypeReference(),
					TypeDeclarationAccessibility.Public,
					options =>
						options with
						{
							IsStatic = true,
							Parameters = [new("onBuilt", TypeIdentity.Create<string>().AsTypeReference())],
						},
					methodBody =>
					{
						methodBody.Assignment(
							"var builder",
							expression => expression.New("global::System.Text.StringBuilder", "onBuilt")
						);
						methodBody.Assignment(
							"global::System.Text.StringBuilder",
							"options",
							expression => expression.New(["onBuilt"])
						);
						methodBody.Return("options.ToString()");
					}
				);
			}
		);

		spc.AddSource($"{target.TypeName}.CodeWriterSample.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
	}
}
