using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Purview.SourceGeneratorFramework.Examples;

/// <summary>
/// Emits source generated by the <see cref="ServiceRegistrationGenerator"/>.
/// </summary>
static class ServiceRegistrationEmitter
{
	/// <summary>
	/// Emits the <c>GenerateServiceAttribute</c> attribute and <c>ServiceLifetime</c> enum
	/// via <see cref="CodeWriter"/>.
	/// </summary>
	public static void EmitAttributeAndEnum(IncrementalGeneratorPostInitializationContext spc)
	{
		CodeWriter writer = new(
			GenerationSettings.Create<ServiceRegistrationGenerator>(),
			throwOnUnclosedScopes: false
		);

		writer.AutoGeneratedHeader();
		writer.FileScopedNamespace(ExampleGenerator.PurviewTypeLibrary.GenerateServiceAttribute);

		writer.Enum(
			ExampleGenerator.PurviewTypeLibrary.ServiceLifetime.Name,
			TypeDeclarationAccessibility.Public,
			options => (options with { IsPartial = false }),
			ew =>
			{
				ew.EnumField("Singleton", 0);
				ew.EnumField("Scoped", 1);
				ew.EnumField("Transient", 2);
			}
		);

		writer.AttributeClass(
			ExampleGenerator.PurviewTypeLibrary.GenerateServiceAttribute.Name,
			TypeDeclarationAccessibility.Public,
			AttributeTargets.Class,
			cw =>
			{
				cw.Constructor(
					"GenerateServiceAttribute",
					TypeDeclarationAccessibility.Public,
					options =>
						(
							options with
							{
								Parameters =
								[
									new("lifetime", ExampleGenerator.PurviewTypeLibrary.ServiceLifetime)
									{
										DefaultValue = "ServiceLifetime.Singleton",
									},
								],
							}
						),
					body => body.Assignment("Lifetime", "lifetime")
				);

				cw.Property(
					"Lifetime",
					ExampleGenerator.PurviewTypeLibrary.ServiceLifetime,
					TypeDeclarationAccessibility.Public
				);

				cw.Property(
					"Name",
					PurviewTypeLibrary.System.String.MakeNullable(cw),
					TypeDeclarationAccessibility.Public,
					options => (options with { HasSetter = true, Initializer = "null" })
				);
			},
			configure: options => (options with { IsPartial = false })
		);

		spc.AddSource("GenerateServiceAttribute.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
	}

	/// <summary>
	/// Emits the <c>ServiceCollectionExtensions</c> class and, optionally, the <c>ServiceInfo</c> class.
	/// </summary>
	public static void Execute(SourceProductionContext spc, ServiceRegistrationGenerationModel model)
	{
		if (model.Context.Settings.IsSourceGeneratorDisabled)
		{
			model.Context.Info("ServiceRegistrationGenerator is disabled.");
			return;
		}

		if (model.Targets.IsEmpty)
		{
			model.Context.Info("No service targets found.");
			return;
		}

		var writer = model.Context.CreateCodeWriter();
		writer.AutoGeneratedHeader();
		writer.FileScopedNamespace(ExampleGenerator.PurviewTypeLibrary.ServiceCollectionExtensions);

		writer.Class(
			ExampleGenerator.PurviewTypeLibrary.ServiceCollectionExtensions.Name,
			TypeDeclarationAccessibility.Public,
			options => (options with { IsStatic = true, IsPartial = false }),
			cw =>
				cw.Method(
					"AddExampleServices",
					ExampleGenerator.PurviewTypeLibrary.Microsoft.Extensions.DependencyInjection.IServiceCollection,
					TypeDeclarationAccessibility.Public,
					options =>
						(
							options with
							{
								IsStatic = true,
								Parameters =
								[
									new(
										"services",
										ExampleGenerator
											.PurviewTypeLibrary
											.Microsoft
											.Extensions
											.DependencyInjection
											.IServiceCollection
									)
									{
										IsThis = true,
									},
								],
							}
						),
					body =>
					{
						foreach (var target in model.Targets)
						{
							body.Comment($"Service name: {target.Name}");
							body.MethodCall(
								$"Add{target.LifetimeMemberName}",
								["services"],
								ExampleGenerator.PurviewTypeLibrary.Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.ToString(),
								[new TypeReference(new TypeIdentity(target.TypeName, null))]
							);
						}

						body.Return("services");
					}
				)
		);

		spc.AddSource("ServiceCollectionExtensions.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));

		if (model.EmitServiceInfo)
			EmitServiceInfo(spc, model);
	}

	static void EmitServiceInfo(SourceProductionContext spc, ServiceRegistrationGenerationModel model)
	{
		var writer = model.Context.CreateCodeWriter();
		writer.AutoGeneratedHeader();
		writer.FileScopedNamespace(ExampleGenerator.PurviewTypeLibrary.ServiceInfo);

		writer.Class(
			ExampleGenerator.PurviewTypeLibrary.ServiceInfo.Name,
			TypeDeclarationAccessibility.Public,
			options => (options with { IsStatic = true, IsPartial = false }),
			cw =>
			{
				foreach (var target in model.Targets)
				{
					cw.Class(
						target.ClassName,
						TypeDeclarationAccessibility.Public,
						options => (options with { IsStatic = true, IsPartial = false }),
						inner =>
						{
							inner.Property(
								"Name",
								TypeIdentity.Create<string>().AsTypeReference(),
								TypeDeclarationAccessibility.Public,
								options =>
									(options with { IsStatic = true, ExpressionBody = target.Name.StringLiteral() })
							);

							inner.Property(
								"Lifetime",
								TypeIdentity.Create<string>().AsTypeReference(),
								TypeDeclarationAccessibility.Public,
								options =>
									(
										options with
										{
											IsStatic = true,
											ExpressionBody = target.LifetimeMemberName.StringLiteral(),
										}
									)
							);

							inner.Property(
								"Type",
								PurviewTypeLibrary.System.Type,
								TypeDeclarationAccessibility.Public,
								options =>
									(options with { IsStatic = true, ExpressionBody = $"typeof({target.TypeName})" })
							);
						}
					);
				}
			}
		);

		spc.AddSource("ServiceInfo.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
	}
}
