namespace Purview.SourceGeneratorFramework.Examples;

/// <summary>
/// Emits a sample class demonstrating the identities exposed by the generated type library. The
/// <c>SampleTypeLibrary</c> spec produces a self-contained type library whose nested
/// <c>public static partial</c> classes expose the declared identities.
/// </summary>
[Generator]
public sealed class TypeLibrarySampleGenerator : IIncrementalGenerator
{
	/// <summary>
	/// Initializes the generator pipeline.
	/// </summary>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static spc =>
		{
			CodeWriter writer = new(GenerationSettings.Create<TypeLibrarySampleGenerator>());

			writer
				.AutoGeneratedHeader()
				.Class(
					new("TypeLibrarySample", TypeDeclarationAccessibility.Internal)
					{
						IsStatic = true,
						IsPartial = false,
					},
					body =>
						body.XmlSummary("The names of the identities exposed by the generated type library.")
							.Field(
								new(
									"SampleAttributeName",
									PurviewTypeLibrary.System.String.AsTypeReference(),
									TypeDeclarationAccessibility.Public
								)
								{
									IsConst = true,
									Initializer =
										$"\"{SampleTypeLibrary.Purview.SourceGeneratorFramework.Examples.GenerateTypeLibrarySampleAttribute.Name}\"",
								}
							)
							.Field(
								new(
									"DebugName",
									PurviewTypeLibrary.System.String.AsTypeReference(),
									TypeDeclarationAccessibility.Public
								)
								{
									IsConst = true,
									Initializer = $"\"{SampleTypeLibrary.System.Diagnostics.Debug.Name}\"",
								}
							)
							.Field(
								new(
									"ILoggerName",
									PurviewTypeLibrary.System.String.AsTypeReference(),
									TypeDeclarationAccessibility.Public
								)
								{
									IsConst = true,
									Initializer = $"\"{SampleTypeLibrary.Microsoft.Extensions.Logging.ILogger.Name}\"",
								}
							)
							.Field(
								new(
									"LogLevelName",
									PurviewTypeLibrary.System.String.AsTypeReference(),
									TypeDeclarationAccessibility.Public
								)
								{
									IsConst = true,
									Initializer = $"\"{SampleTypeLibrary.Microsoft.Extensions.Logging.LogLevel.Name}\"",
								}
							)
							.Field(
								new(
									"EventIdName",
									PurviewTypeLibrary.System.String.AsTypeReference(),
									TypeDeclarationAccessibility.Public
								)
								{
									IsConst = true,
									Initializer = $"\"{SampleTypeLibrary.Microsoft.Extensions.Logging.EventId.Name}\"",
								}
							)
							.Field(
								new(
									"LoggerMessageName",
									PurviewTypeLibrary.System.String.AsTypeReference(),
									TypeDeclarationAccessibility.Public
								)
								{
									IsConst = true,
									Initializer =
										$"\"{SampleTypeLibrary.Microsoft.Extensions.Logging.LoggerMessage.Name}\"",
								}
							)
							.Field(
								new(
									"SampleItemsType",
									PurviewTypeLibrary.System.String.AsTypeReference(),
									TypeDeclarationAccessibility.Public
								)
								{
									IsConst = true,
									Initializer =
										$"\"{SampleTypeLibrary.System.Collections.Generic.SampleItems.Identity.Name}\"",
								}
							)
							.Field(
								new(
									"InheritedStringName",
									PurviewTypeLibrary.System.String.AsTypeReference(),
									TypeDeclarationAccessibility.Public
								)
								{
									IsConst = true,
									Initializer = $"\"{SampleTypeLibrary.System.String.Name}\"",
								}
							)
							.Field(
								new(
									"LoggingTypesCount",
									PurviewTypeLibrary.System.Int32.AsTypeReference(),
									TypeDeclarationAccessibility.Public
								)
								{
									IsConst = true,
									Initializer = $"{SampleTypeLibrary.Microsoft.Extensions.Logging.GetTypes().Length}",
								}
							)
				);

			spc.AddSource("TypeLibrarySample.g.cs", writer);
		});
	}
}
