using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Purview.SourceGeneratorFramework.Generators.Helpers;
using Purview.SourceGeneratorFramework.Logging;

namespace Purview.SourceGeneratorFramework.Generators;

[Generator]
public sealed class AttributeDataModelGenerator : IIncrementalGenerator
{
	static TypeReference TypeReference(string typeName) => new(new TypeIdentity(typeName, null));

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context
			.RegisterEmbeddedAttribute<AttributeDataModelGenerator>()
			.RegisterPostInitializationOutput(context =>
			{
				foreach (var (hintName, source) in SourceEmitter.AttributeDataEmit())
					context.AddSource(hintName, source);
			});

		var targetPipeline = AttributeDataModelLibrary.GetAttributeTargetPipeline(context);
		var contextPipeline = IncrementalPipeline.DefaultGenerationContextValueProvider<AttributeDataModelGenerator>(
			context,
			PropertyLibrary.DisableAttributeDataSourceGenerator
		);

		var outputPipeline = targetPipeline.CombineWithContext(contextPipeline);

		context.RegisterSourceOutput(
			outputPipeline,
			static (spc, outputContext) =>
			{
				var (target, generationContext) = outputContext;

				if (generationContext.Settings.IsSourceGeneratorDisabled)
				{
					generationContext.Info("AttributeDataModelGenerator is disabled.");
					return;
				}

				// Validation diagnostics (ADM0001-ADM0010) are reported by the analyzers; the generator only
				// skips processing targets that carry a blocking error.
				if (!target.ShouldProcess)
					return;

				GenerateAttributeDataModel(spc, target.Value, generationContext);
			}
		);
	}

	static void GenerateAttributeDataModel(
		SourceProductionContext spc,
		AttributeDataModelTarget target,
		GenerationContext<EmptyCapabilities> generationContext
	)
	{
		generationContext.Debug("Generating AttributeDataModel for {0}", target.StructName);

		var writer = generationContext.CreateCodeWriter();

		writer.AutoGeneratedHeader();
		writer.Using("Purview.SourceGeneratorFramework").NewLine();
		writer.Using("Microsoft.CodeAnalysis").NewLine();

		if (string.IsNullOrEmpty(target.Namespace))
		{
			Struct(writer, target);
		}
		else
		{
			using (writer.BlockNamespaceScope(target.Namespace))
				Struct(writer, target);
		}

		spc.AddSource($"{target.StructName}.AttributeDataModel.g.cs", writer);
	}

	static void Struct(CodeWriter writer, AttributeDataModelTarget target)
	{
		TypeDeclarationOptions options = new(target.StructName, target.Accessibility)
		{
			IsReadOnly = target.IsReadOnly,
			IsPartial = true,
		};

		using (target.IsRecord ? writer.RecordStructScope(options) : writer.StructScope(options))
		{
			writer.Property(new("Exists", TypeReference("bool"), TypeDeclarationAccessibility.Public));

			foreach (var property in target.Properties)
			{
				if (property.IsExplicit)
					continue;

				writer.Property(
					new(
						property.PropertyName,
						TypeReference(property.FullyQualifiedTypeName),
						TypeDeclarationAccessibility.Public
					)
					{
						IsInitOnly = true,
					}
				);
			}

			Constructor(writer, target);
			TargetAttributeField(writer, target);
			EmptyField(writer, target);
			AllAttributeDataMethod(writer, target);
			AllAttributeDataSymbolMethod(writer, target);

			FromAttributeDataArrayMethod(writer, target);

			// ISymbol attribute extraction methods with out parameters
			FromAttributeDataSymbolMethod(writer, target);
			TryFromAttributeDataSymbolMethod(writer, target);

			// AttributeData array extraction methods with out parameters
			FromAttributeDataArrayWithOutMethod(writer, target);
			TryFromAttributeDataArrayWithOutMethod(writer, target);

			// ISymbol attribute extraction methods with out parameters
			FromAttributeDataSymbolWithOutMethod(writer, target);
			TryFromAttributeDataSymbolWithOutMethod(writer, target);

			// AttributeData extraction methods
			FromAttributeDataMethod(writer, target);
			TryFromAttributeDataMethod(writer, target);
		}
	}

	static void Constructor(CodeWriter writer, AttributeDataModelTarget target)
	{
		var parameters = ImmutableArray.CreateBuilder<ParameterDeclarationOptions>();
		parameters.Add(new("exists", TypeReference("bool")));

		foreach (var property in target.Properties)
		{
			parameters.Add(new(property.PropertyName, TypeReference(property.FullyQualifiedTypeName)));
		}

		writer.Constructor(
			new(target.StructName, TypeDeclarationAccessibility.Public)
			{
				Parameters = [.. parameters],
				Initializer = GetPrimaryConstructorInitializer(target),
			},
			body =>
			{
				body.Assignment("Exists", "exists");
				foreach (var property in target.Properties)
				{
					if (!property.IsExplicit)
						body.Assignment($"this.{property.PropertyName}", property.PropertyName);
				}
			}
		);
	}

	static string? GetPrimaryConstructorInitializer(AttributeDataModelTarget target)
	{
		return target.PrimaryConstructorArguments.IsEmpty
			? null
			: $"this({string.Join(", ", target.PrimaryConstructorArguments)})";
	}

	static void TargetAttributeField(CodeWriter writer, AttributeDataModelTarget target)
	{
		writer.Field(
			new(
				"TargetAttribute",
				GeneratorTypeLibrary.TypeValueObject.AsTypeReference(),
				TypeDeclarationAccessibility.Public
			)
			{
				IsStatic = true,
				IsReadOnly = true,
				Initializer = $"new(\"{target.TargetAttribute.Name}\", \"{target.TargetAttribute.Namespace}\")",
			}
		);
	}

	static void EmptyField(CodeWriter writer, AttributeDataModelTarget target)
	{
		List<string> values = ["false"];
		foreach (var property in target.Properties)
		{
			var value = $"default({property.FullyQualifiedTypeName})";
			if (property.IsNonNullableReferenceType)
				value += "!";

			values.Add(value);
		}

		writer.Field(
			new("Empty", TypeReference(target.StructName), TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				IsReadOnly = true,
				Initializer = $"new({string.Join(", ", values)})",
			}
		);
	}

	static void AllAttributeDataMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		var returnType = TypeReference(
			$"global::System.Collections.Generic.IEnumerable<({target.StructName} Instance, global::Microsoft.CodeAnalysis.AttributeData Attribute)>"
		);
		MethodDeclarationOptions methodOptions = new(
			"AllAttributeData",
			returnType,
			TypeDeclarationAccessibility.Public
		)
		{
			IsStatic = true,
			Parameters =
			[
				new(
					"attributes",
					TypeReference(
						"global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.AttributeData>"
					)
				),
			],
		};

		writer.Method(
			methodOptions,
			body =>
			{
				body.Line("for (var i = 0; i < attributes.Length; i++)");
				body.Block(
					null,
					loopBody =>
					{
						loopBody.Line("var instance = FromAttributeData(attributes[i]);");
						loopBody.Line("if (instance.Exists)");
						loopBody.Block(null, matchBody => matchBody.Line("yield return (instance, attributes[i]);"));
					}
				);
			}
		);
	}

	static void AllAttributeDataSymbolMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		var returnType = TypeReference(
			$"global::System.Collections.Generic.IEnumerable<({target.StructName} Instance, global::Microsoft.CodeAnalysis.AttributeData Attribute)>"
		);
		writer.Method(
			new MethodDeclarationOptions("AllAttributeData", returnType, TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				Parameters = [new("symbol", TypeReference("global::Microsoft.CodeAnalysis.ISymbol"))],
			},
			body => body.Line("return AllAttributeData(symbol.GetAttributes());")
		);
	}

	static void FromAttributeDataArrayMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		MethodDeclarationOptions methodOptions = new(
			"FromAttributeData",
			TypeReference(target.StructName),
			TypeDeclarationAccessibility.Public
		)
		{
			IsStatic = true,
			Parameters =
			[
				new(
					"attributes",
					TypeReference(
						"global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.AttributeData>"
					)
				),
			],
		};

		writer.Method(
			methodOptions,
			w =>
			{
				w.Line("for (var i = 0; i < attributes.Length; i++)");
				w.Block(
					null,
					body =>
					{
						body.Line("var result = FromAttributeData(attributes[i]);");
						body.Line("if (result.Exists)");
						body.Block(null, inner => inner.Line("return result;"));
					}
				);
				w.Line("return Empty;");
			}
		);
	}

	static void FromAttributeDataSymbolMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		writer.Method(
			new("FromAttributeData", TypeReference(target.StructName), TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				Parameters = [new("symbol", TypeReference("global::Microsoft.CodeAnalysis.ISymbol"))],
			},
			body => body.Line("return FromAttributeData(symbol.GetAttributes());")
		);
	}

	static void TryFromAttributeDataSymbolMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		writer.Method(
			new("TryFromAttributeData", PurviewTypeLibrary.System.Boolean, TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				Parameters =
				[
					new("symbol", TypeReference("global::Microsoft.CodeAnalysis.ISymbol")),
					new("attributeData", TypeReference(target.StructName), ParameterModifier.Out),
				],
			},
			body => body.Line("return TryFromAttributeData(symbol.GetAttributes(), out attributeData, out _);")
		);
	}

	static void FromAttributeDataArrayWithOutMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		MethodDeclarationOptions methodOptions = new(
			"FromAttributeData",
			TypeReference(target.StructName),
			TypeDeclarationAccessibility.Public
		)
		{
			IsStatic = true,
			Parameters =
			[
				new(
					"attributes",
					TypeReference(
						"global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.AttributeData>"
					)
				),
				new("attribute", TypeReference("global::Microsoft.CodeAnalysis.AttributeData?"))
				{
					Modifier = ParameterModifier.Out,
				},
			],
		};

		writer.Method(
			methodOptions,
			w =>
			{
				w.Line("attribute = null;");
				w.Line("for (var i = 0; i < attributes.Length; i++)");
				w.Block(
					null,
					body =>
					{
						body.Line("var result = FromAttributeData(attributes[i]);");
						body.Line("if (result.Exists)");
						body.Block(
							null,
							inner =>
							{
								inner.Line("attribute = attributes[i];");
								inner.Line("return result;");
							}
						);
					}
				);
				w.Line("return Empty;");
			}
		);
	}

	static void TryFromAttributeDataArrayWithOutMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		MethodDeclarationOptions methodOptions = new(
			"TryFromAttributeData",
			PurviewTypeLibrary.System.Boolean,
			TypeDeclarationAccessibility.Public
		)
		{
			IsStatic = true,
			Parameters =
			[
				new(
					"attributes",
					TypeReference(
						"global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.AttributeData>"
					)
				),
				new("attributeData", TypeReference(target.StructName)) { Modifier = ParameterModifier.Out },
				new("attribute", TypeReference("global::Microsoft.CodeAnalysis.AttributeData?"))
				{
					Modifier = ParameterModifier.Out,
				},
			],
		};

		writer.Method(
			methodOptions,
			w =>
			{
				w.Assignment("attributeData", "Empty");
				w.Assignment("attribute", "null");

				w.Line("for (var i = 0; i < attributes.Length; i++)");
				w.Block(
					null,
					body =>
					{
						body.Line("var result = FromAttributeData(attributes[i]);");
						body.Line("if (result.Exists)");
						body.Block(
							null,
							inner =>
							{
								inner.Line("attribute = attributes[i];");
								inner.Line("attributeData = result;");
								inner.Line("return true;");
							}
						);
					}
				);
				w.Line("return false;");
			}
		);
	}

	static void FromAttributeDataSymbolWithOutMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		writer.Method(
			new MethodDeclarationOptions(
				"FromAttributeData",
				TypeReference(target.StructName),
				TypeDeclarationAccessibility.Public
			)
			{
				IsStatic = true,
				Parameters =
				[
					new("symbol", TypeReference("global::Microsoft.CodeAnalysis.ISymbol")),
					new("attribute", TypeReference("global::Microsoft.CodeAnalysis.AttributeData?"))
					{
						Modifier = ParameterModifier.Out,
					},
				],
			},
			body => body.Line("return FromAttributeData(symbol.GetAttributes(), out attribute);")
		);
	}

	static void TryFromAttributeDataSymbolWithOutMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		writer.Method(
			new MethodDeclarationOptions(
				"TryFromAttributeData",
				TypeReference(PurviewTypeLibrary.System.Boolean),
				TypeDeclarationAccessibility.Public
			)
			{
				IsStatic = true,
				Parameters =
				[
					new("symbol", TypeReference("global::Microsoft.CodeAnalysis.ISymbol")),
					new("attributeData", TypeReference(target.StructName), ParameterModifier.Out),
					new(
						"attribute",
						TypeReference("global::Microsoft.CodeAnalysis.AttributeData?"),
						ParameterModifier.Out
					)
					{
						Modifier = ParameterModifier.Out,
					},
				],
			},
			body => body.Line("return TryFromAttributeData(symbol.GetAttributes(), out attributeData, out attribute);")
		);
	}

	static void FromAttributeDataMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		MethodDeclarationOptions methodOptions = new(
			"FromAttributeData",
			TypeReference(target.StructName),
			TypeDeclarationAccessibility.Public
		)
		{
			IsStatic = true,
			Parameters = [new("attributeData", TypeReference("global::Microsoft.CodeAnalysis.AttributeData"))],
		};

		writer.Method(
			methodOptions,
			w =>
			{
				if (target.MatchByInheritance)
				{
					w.Line(
						"if (attributeData.AttributeClass is null || (!TargetAttribute.Equals(attributeData.AttributeClass) && !global::Purview.SourceGeneratorFramework.Helpers.TypeHelpers.InheritsFrom(attributeData.AttributeClass, TargetAttribute)))"
					);
				}
				else
				{
					w.Line("if (!TargetAttribute.Equals(attributeData.AttributeClass))");
				}
				w.Block(null, body => body.Line("return Empty;"));

				foreach (var property in target.Properties)
				{
					PropertyExtraction(w, property);
				}

				List<string> returnValues = ["true"];
				foreach (var property in target.Properties)
				{
					var value = ToCamelCase(property.PropertyName);
					returnValues.Add(property.IsNonNullableReferenceType ? value + "!" : value);
				}

				w.Line($"return new({string.Join(", ", returnValues)});");
			}
		);
	}

	static void TryFromAttributeDataMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		MethodDeclarationOptions methodOptions = new(
			"TryFromAttributeData",
			PurviewTypeLibrary.System.Boolean,
			TypeDeclarationAccessibility.Public
		)
		{
			IsStatic = true,
			Parameters =
			[
				new("attributeData", TypeReference("global::Microsoft.CodeAnalysis.AttributeData")),
				new("attribute", TypeReference(target.StructName), ParameterModifier.Out),
			],
		};

		writer.Method(
			methodOptions,
			w =>
			{
				w.Assignment("attribute", "Empty");
				if (target.MatchByInheritance)
				{
					w.Line(
						"if (attributeData.AttributeClass is null || (!TargetAttribute.Equals(attributeData.AttributeClass) && !global::Purview.SourceGeneratorFramework.Helpers.TypeHelpers.InheritsFrom(attributeData.AttributeClass, TargetAttribute)))"
					);
				}
				else
				{
					w.Line("if (!TargetAttribute.Equals(attributeData.AttributeClass))");
				}
				w.Block(null, body => body.Line("return false;"));

				foreach (var property in target.Properties)
				{
					PropertyExtraction(w, property);
				}

				List<string> returnValues = ["true"];
				foreach (var property in target.Properties)
				{
					var value = ToCamelCase(property.PropertyName);
					returnValues.Add(property.IsNonNullableReferenceType ? value + "!" : value);
				}

				w.Assignment("attribute", $"new({string.Join(", ", returnValues)})");

				w.Return("attribute.Exists");
			}
		);
	}

	static void PropertyExtraction(CodeWriter writer, AttributeDataModelProperty property)
	{
		var variableName = ToCamelCase(property.PropertyName);
		var typeName = GetNonNullableTypeName(property.FullyQualifiedTypeName);
		var localTypeName =
			property.IsNullableValueType ? typeName
			: property.IsNonNullableReferenceType ? typeName + "?"
			: property.FullyQualifiedTypeName;

		if (property.IsNestedModel)
		{
			writer.Line($"var {variableName} = {property.NestedModelTypeName}.FromAttributeData(attributeData);");
			return;
		}

		if (property.IsEnum)
		{
			EnumPropertyExtraction(writer, property, variableName);
			return;
		}

		var sources = property.Sources.AsImmutableArray();
		if (sources.IsEmpty)
		{
			writer.Line($"var {variableName} = default({typeName});");
			return;
		}

		if (sources.Length == 1)
		{
			var source = sources[0];
			if (property.HasDefaultValue)
			{
				SingleSourceExtractionWithDefault(
					writer,
					source,
					variableName,
					typeName,
					property.DefaultValueExpression
				);
			}
			else
			{
				SingleSourceExtraction(writer, source, variableName, typeName);
			}
			return;
		}

		MultiSourceExtraction(
			writer,
			sources,
			variableName,
			typeName,
			localTypeName,
			property.HasDefaultValue,
			property.DefaultValueExpression
		);
	}

	static void SingleSourceExtraction(CodeWriter writer, PropertySource source, string variableName, string typeName)
	{
		var extraction = GetSingleSourceExtractionExpression(source, variableName, typeName);
		writer.Line(extraction);
	}

	static void SingleSourceExtractionWithDefault(
		CodeWriter writer,
		PropertySource source,
		string variableName,
		string typeName,
		string defaultValueExpression
	)
	{
		var extraction = GetSingleSourceExtractionWithDefaultExpression(
			source,
			variableName,
			typeName,
			defaultValueExpression
		);
		writer.Line(extraction);
	}

	static void MultiSourceExtraction(
		CodeWriter writer,
		ImmutableArray<PropertySource> sources,
		string variableName,
		string typeName,
		string localTypeName,
		bool hasDefaultValue,
		string defaultValueExpression
	)
	{
		writer.Line($"{localTypeName} {variableName};");

		void Fallback(int index)
		{
			if (index >= sources.Length)
			{
				if (hasDefaultValue)
				{
					writer.Line($"{variableName} = {defaultValueExpression};");
				}
				return;
			}

			var source = sources[index];
			var isLast = index == sources.Length - 1 && !hasDefaultValue;
			var methodCall = GetTryGetMethodCall(source, variableName, typeName, declareVariable: false);

			if (isLast)
			{
				writer.Line(methodCall + ";");
			}
			else
			{
				writer.Line($"if (!{methodCall})");
				writer.Block(null, body => Fallback(index + 1));
			}
		}

		Fallback(0);
	}

	static void EnumPropertyExtraction(CodeWriter writer, AttributeDataModelProperty property, string variableName)
	{
		var sources = property.Sources.AsImmutableArray();
		var defaultValueExpression = property.HasDefaultValue ? property.DefaultValueExpression : "null";

		if (sources.Length == 1)
		{
			var expression = GetEnumSingleSourceExtractionExpression(sources[0], defaultValueExpression);
			writer.Line($"var {variableName} = {expression};");
			return;
		}

		EnumMultiSourceExtraction(writer, sources, variableName, defaultValueExpression);
	}

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	static string GetEnumSingleSourceExtractionExpression(PropertySource source, string defaultValueExpression)
	{
		return source.Source switch
		{
			AttributePropertySource.NamedArgument =>
				$"attributeData.GetEnumNamedArgument(\"{source.MappedName}\", {defaultValueExpression})",
			AttributePropertySource.ConstructorIndex =>
				$"attributeData.GetEnumConstructorArgument({source.ConstructorIndex}, {defaultValueExpression})",
			AttributePropertySource.ConstructorName =>
				$"attributeData.GetEnumConstructorArgument(\"{source.MappedName}\", {defaultValueExpression})",
			_ => throw new InvalidOperationException($"Unsupported enum property source: {source.Source}"),
		};
	}

	static void EnumMultiSourceExtraction(
		CodeWriter writer,
		ImmutableArray<PropertySource> sources,
		string variableName,
		string defaultValueExpression
	)
	{
		var typeName = "global::Microsoft.CodeAnalysis.TypedConstant";
		var tempName = $"__{variableName}Tc";

		writer.Line($"{typeName} {tempName} = default;");

		void Fallback(int index)
		{
			if (index >= sources.Length)
			{
				writer.Line($"{tempName} = default;");
				return;
			}

			var source = sources[index];
			var isLast = index == sources.Length - 1;
			var methodCall = GetTryGetMethodCall(source, tempName, typeName, declareVariable: false);

			if (isLast)
			{
				writer.Line(methodCall + ";");
			}
			else
			{
				writer.Line($"if (!{methodCall})");
				writer.Block(null, body => Fallback(index + 1));
			}
		}

		Fallback(0);

		writer.Line($"var {variableName} = {tempName}.ToEnumString() ?? {defaultValueExpression};");
	}

	static string GetSingleSourceExtractionExpression(PropertySource source, string variableName, string typeName)
	{
		var methodCall = GetTryGetMethodCall(source, variableName, typeName, declareVariable: true);
		// TryGet method declares the variable via out var, so we just call it.
		return methodCall + ";";
	}

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	static string GetSingleSourceExtractionWithDefaultExpression(
		PropertySource source,
		string variableName,
		string typeName,
		string defaultValueExpression
	)
	{
		return source.Source switch
		{
			AttributePropertySource.NamedArgument =>
				$"var {variableName} = attributeData.GetNamedArgument<{typeName}>(\"{source.MappedName}\", {defaultValueExpression});",
			AttributePropertySource.ConstructorIndex =>
				$"var {variableName} = attributeData.GetConstructorArgument<{typeName}>({source.ConstructorIndex}, {defaultValueExpression});",
			AttributePropertySource.ConstructorName =>
				$"var {variableName} = attributeData.GetConstructorArgument<{typeName}>(\"{source.MappedName}\", {defaultValueExpression});",
			AttributePropertySource.TypeArgument when source.MappedName is not null =>
				$"var {variableName} = attributeData.GetGenericTypeArgument<{typeName}>(\"{source.MappedName}\", {defaultValueExpression});",
			AttributePropertySource.TypeArgument =>
				$"var {variableName} = attributeData.GetGenericTypeArgument<{typeName}>({source.ConstructorIndex}, {defaultValueExpression});",
			_ => throw new InvalidOperationException($"Unsupported property source: {source.Source}"),
		};
	}

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	static string GetTryGetMethodCall(PropertySource source, string variableName, string typeName, bool declareVariable)
	{
		var outVariable = declareVariable ? $"out var {variableName}" : $"out {variableName}";
		return source.Source switch
		{
			AttributePropertySource.NamedArgument =>
				$"attributeData.TryGetNamedArgument<{typeName}>(\"{source.MappedName}\", {outVariable})",
			AttributePropertySource.ConstructorIndex =>
				$"attributeData.TryGetConstructorArgument<{typeName}>({source.ConstructorIndex}, {outVariable})",
			AttributePropertySource.ConstructorName =>
				$"attributeData.TryGetConstructorArgument<{typeName}>(\"{source.MappedName}\", {outVariable})",
			AttributePropertySource.TypeArgument when source.MappedName is not null =>
				$"attributeData.TryGetGenericTypeArgument<{typeName}>(\"{source.MappedName}\", {outVariable})",
			AttributePropertySource.TypeArgument =>
				$"attributeData.TryGetGenericTypeArgument<{typeName}>({source.ConstructorIndex}, {outVariable})",
			_ => throw new InvalidOperationException($"Unsupported property source: {source.Source}"),
		};
	}

	static string GetNonNullableTypeName(string typeName) =>
		typeName.EndsWith("?", StringComparison.Ordinal) ? typeName.Substring(0, typeName.Length - 1) : typeName;

	static string ToCamelCase(string value) =>
		string.IsNullOrEmpty(value) ? value : char.ToLowerInvariant(value[0]) + value.Substring(1);
}
